# Generated by Django 5.1.4 on 2024-12-21 00:28

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboratorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre por defecto', max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='LaboratorioModel',
        ),
        migrations.AlterModelOptions(
            name='directorgeneral',
            options={'verbose_name_plural': 'Directores Generales'},
        ),
        migrations.RemoveField(
            model_name='producto',
            name='f_fabricacion',
        ),
        migrations.AddField(
            model_name='producto',
            name='fecha_fabricacion',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 1, 0, 0), validators=[django.core.validators.MinValueValidator(datetime.datetime(2015, 1, 1, 0, 0))]),
        ),
        migrations.AlterField(
            model_name='directorgeneral',
            name='nombre',
            field=models.CharField(default='Nombre por defecto', max_length=255),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(default='Nombre por defecto', max_length=255),
        ),
        migrations.AddField(
            model_name='directorgeneral',
            name='laboratorio',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorio'),
        ),
        migrations.AddField(
            model_name='producto',
            name='laboratorio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorio'),
        ),
    ]
