# Generated by Django 5.1.4 on 2024-12-21 00:47

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_laboratorio_delete_laboratoriomodel_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='fecha_fabricacion',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 1, 0, 0), validators=[django.core.validators.MinValueValidator(datetime.datetime(2015, 1, 1, 0, 0))]),
        ),
    ]
