# Generated by Django 5.1.4 on 2024-12-21 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0004_alter_producto_fecha_fabricacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='fecha_fabricacion',
        ),
    ]
