# Generated by Django 5.1.4 on 2024-12-21 00:55

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0005_remove_producto_fecha_fabricacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='fecha_fabricacion',
            field=models.DateTimeField(default=datetime.datetime(2015, 1, 1, 0, 0), validators=[django.core.validators.MinValueValidator(datetime.datetime(2015, 1, 1, 0, 0))]),
        ),
    ]
