# Generated by Django 5.1.4 on 2024-12-27 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0009_alter_producto_fecha_fabricacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='p_costo',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
        migrations.AlterField(
            model_name='producto',
            name='p_venta',
            field=models.DecimalField(decimal_places=2, max_digits=13),
        ),
    ]
