# Generated by Django 5.1.4 on 2024-12-27 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0010_actualizado_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(default='Ciudad por defecto', max_length=255),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(default='Pais por defecto', max_length=255),
        ),
    ]
