# Generated by Django 5.1.4 on 2024-12-27 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0012_alter_laboratorio_ciudad_alter_laboratorio_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visitas', models.IntegerField(default=0)),
            ],
        ),
    ]
