# Generated by Django 5.1.4 on 2024-12-28 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0013_contador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laboratorio',
            name='ciudad',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='laboratorio',
            name='pais',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
