# Generated by Django 5.1.4 on 2025-01-17 22:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0014_alter_laboratorio_ciudad_alter_laboratorio_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='laboratorio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='laboratorio.laboratorio'),
        ),
    ]
